version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
